Repository DerangedSenators/PlayerLink, pull requests merged in 2020-12, with the labels that each got.

#29 GameServer: Remove redundant commented out code
  server/net/GameServer.h
Labels: Optimisation

#34 Logfile
  CMakeLists.txt
  core/net/SocketException.h
  core/utils/exceptions/RuntimeException.cpp
  core/utils/exceptions/RuntimeException.h
  core/utils/logger/LogSeverity.h
  core/utils/logger/Logger.cpp
  core/utils/logger/Logger.h
Labels: feature

#37 Add initaliser for WinSock2.dll
  CMakeLists.txt
  core/net/tcp/tcpsocket.h
  platform/microsoft/win32/overlays/core/net/winsockinit.c
  platform/microsoft/win32/overlays/core/net/winsockinit.h
Labels: bug

#42 Add some documentation
  .gitignore
  docs/Architecture/Overlay System.md
  docs/Architecture/PlayerLink Repository.md
Labels: documentation
